    - name: Install go repository
      apt_repository: repo="deb http://dl.bintray.com/gocd/gocd-deb/ /" state=present update_cache=yes
      sudo: yes

    - name: Install avahi
      apt: pkg=avahi-daemon
      sudo: yes
      notify:
      - Update avahi configuration
      - Restart avahi

    - name: Install git
      apt: pkg=git-core
      sudo: yes

    - name: Install go repository key
      apt_key: url=https://bintray.com/user/downloadSubjectPublicKey?username=gocd
      sudo: yes

    - name: Install go server
      apt: pkg=go-server force=yes
      sudo: yes

    - name: Setup ssh key
      user: name=go generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
      sudo: yes

    - name: Turn off strict host checking for github
      lineinfile: dest=/var/go/.ssh/config line='{{ item }}' owner=go group=go mode=0600 create=yes
      with_items:
      - Host github.com
      -     User                    git
      -     IdentityFile            ~/.ssh/id_rsa
      -     StrictHostKeyChecking   no
      -     PasswordAuthentication  no
      -     CheckHostIP             no
      -     BatchMode               yes
      sudo: yes
